name: Deploy Hexo Blog

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install --force

      - name: Install hexo-cli globally
        run: npm install -g hexo-cli

      - name: Clone NexT theme
        run: |
          if [ ! -d "themes/next" ]; then
            git clone https://github.com/next-theme/hexo-theme-next themes/next
          fi

      - name: Build Hexo
        run: |
          npx hexo clean
          npx hexo generate

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          cname: article.freemankevin.uk

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: hexo-build
          path: public/
          retention-days: 7